### ISSUE TITLE
Code for finetuning the instruct models

### ISSUE THREAD

**Issue by bil-ash** [huggingface/smollm#2]
@loubnabnl The code for finetuning the base models are provided in this repo. However, I guess that the same code cannot be used for finetuning the instruct models. So, please provide code for finetuning the instruct models.

**Comment by loubnabnl** [comment]
Hi, the current script should work if you change the dataset content column with properly formatted with ChatML conversations. But we added the recipe for building SmolLM2 instruct  with the alignment handbook here https://github.com/huggingface/alignment-handbook/blob/main/recipes/smollm2/README.md
