### ISSUE TITLE
code of SMOL-VLM-Instruct?

### ISSUE THREAD

**Issue by Debolena7** [huggingface/smollm#36]
Could you please provide the code of SMOL-VLM? We cannot access the layers for fine-tuning otherwise.

**Comment by andimarafioti** [comment]
Hi Debolena, the code is on the transformers repo, it's the same as idefics3, so here:
https://github.com/huggingface/transformers/blob/main/src/transformers/models/idefics3/modeling_idefics3.py
Further, if you want to fine tune it, you can start here:
https://github.com/huggingface/smollm/blob/main/finetuning/Smol_VLM_FT.ipynb
