### ISSUE TITLE
smollm1 135M LR scheduler config

### ISSUE THREAD

**Issue by RmZeta2718** [huggingface/smollm#37]
The authors claim in the [blog](https://huggingface.co/blog/smollm) that smollm1 135M/360M is trained on 600B tokens, which I expect to be 600k steps with 1M token/step.

But in the config of the 135M model ([here](https://github.com/huggingface/smollm/blob/58c5cc63d2d993c441ae5e4ee5ed40cfc567332d/pre-training/smollm1/config_smollm1_135M.yaml#L71)), it seems that the lr decays to 0 at 300k step (decay starts at 250k step and decays to 0 in 50k steps), so lr from 300k to 600k steps is all zero. I'm so confused because train_steps is set to 600k, which is inconsistent with the lr scheduler config IMO.

I believe lr scheduler config in the 360M model ([here](https://github.com/huggingface/smollm/blob/58c5cc63d2d993c441ae5e4ee5ed40cfc567332d/pre-training/smollm1/config_smollm1_360M.yaml#L71)) is the correct setting.

I hope the authors could explain the configuration file or correct me if I have misunderstood it.

**Comment by eliebak** [comment]
Hello, yes you are right, just merge a PR to fix it thanks!
