### ISSUE TITLE
Request for SmolMLv1 Pretraining Code

### ISSUE THREAD

**Issue by JT-Ushio** [huggingface/smollm#5]
Hi, thank you for the amazing work! I'm interested in reproducing the pretraining process of SmolMLv1 (135M) on the SmolLM-Corpus. However, I noticed that the repository currently only includes fine-tuning scripts. Could you please share the pretraining code or provide a tutorial? I would greatly appreciate your help.

Thank you!

**Comment by loubnabnl** [comment]
Hi, we use nanotron for the pre-training https://github.com/huggingface/nanotron/

Here's the config for training SmolLM v1 135M
https://gist.github.com/eliebak/4263659706519536b7eebfe6d9815c60
You might need to adapt the dataset part to use [nanosets](https://github.com/huggingface/nanotron/blob/42040aee8b93964fc19ca194d14fae08d327eacf/docs/nanoset.md#nanosets) with tokenized datasets cc @eliebak

**Comment by ceferisbarov** [comment]
Hi, @loubnabnl ! Thanks for sharing the config file, but it doesn't work with last commit of nanotron:

```
dacite.exceptions.UnexpectedDataError: can not match "launch_slurm_config", "logs_path", "slurm_logs_path", "launch_script_path", "temp_dir", "timestamp_with_run", "config_logs_path", "evals_logs_path", "eval_slurm_config" to any data class field
```

I am also struggling to find a proper documentation of these fields from Nanotron, which makes it hard to debug.

**Comment by eliebak** [comment]
Hey @ceferisbarov,  the fields were not defined in the main version of Nanotron as you mentioned, I updated the config in #6 and it should work with the last commit of nanotron now!

**Comment by ceferisbarov** [comment]
It works now. Thanks! @eliebak

**Comment by JT-Ushio** [comment]
Hi, @eliebak, Thanks for updating the pretraining config. My reproduction is going smoothly except for the issue with [`datasets/stackoverflow`](https://github.com/huggingface/smollm/blob/58c5cc63d2d993c441ae5e4ee5ed40cfc567332d/pre-training/smollm1/config_smollm1_135M.yaml#L17). I am using the [`bigcode/stackoverflow-clean`](https://huggingface.co/datasets/bigcode/stackoverflow-clean) dataset, but I encountered an error when using `nanosets` for preprocessing. I would like to confirm if the dataset I am using is correct.

- Preprocessing command:
```bash
python preprocess_data.py --tokenizer-name-or-path ~/data/hf_home/SmolLM-135M/tokenizer.json --output-folder datasets/stackoverflow --n-tasks 8 hf --dataset ~/public/corpus/bigcode/stackoverflow-clean/
```

- Error message:
```
TypeError: unsupported operand type(s) for |: 'str' and 'dict'
```

**Comment by eliebak** [comment]
can you add `--column content` ?
```
python preprocess_data.py --tokenizer-name-or-path ~/data/hf_home/SmolLM-135M/tokenizer.json --output-folder datasets/stackoverflow --n-tasks 8 hf --dataset ~/public/corpus/bigcode/stackoverflow-clean/ --column content
```
If not working can you send the full error trace?

**Comment by JT-Ushio** [comment]
Thank you very much, it works!

Additionally, I would like to confirm whether the dataset corresponding to datasets/open-web-math is [open-web-math/open-web-math](https://huggingface.co/datasets/open-web-math/open-web-math). Also, I noticed that the datasets/python-edu does not have a default "text" column. Does it require a special `--column`?

**Comment by eliebak** [comment]
yes it's this one for smollm1, for python-edu you need to follow this  https://huggingface.co/datasets/HuggingFaceTB/smollm-corpus#downloading-the-data to download the data!

**Comment by JT-Ushio** [comment]
Thank you for your time and help! The preprocessing for all five datasets is completed. 
No more questions.
